# @copyright (c) 2022-present Skolkovo Institute of Science and Technology
#                              (Skoltech), Russia. All rights reserved.
#                2023-present Artificial Intelligence Research Institute
#                              (AIRI), Russia. All rights reserved.
#
# NNTile is software framework for fast training of big neural networks on
# distributed-memory heterogeneous systems based on StarPU runtime system.
#
# @file nntile/cmake/NNTileSubsystems.cmake
# NNTileSubsystems.cmake
#
# @version 1.1.0
# @file nntile/cmake/NNTileSubsystems.cmake
# Per-subsystem build options and presets for unified target nntile.
# Stack (bottom to top): kernel -> starpu -> core -> tile -> tensor -> nn

option(BUILD_NNTILE "Build unified nntile library" ON)

set(NNTILE_COMPILE_CHECK_SUBSYSTEM "" CACHE STRING
    "Compile-check one subsystem only (kernel|starpu|core|tile|tensor|nn|...) or OFF")

set(NNTILE_PRESET "" CACHE STRING "core|graph_min|full")

function(nntile_subsystem_option NAME DESCRIPTION PARENT)
    option(NNTILE_BUILD_${NAME} "${DESCRIPTION}" ON)
    if(PARENT AND NOT NNTILE_BUILD_${PARENT})
        set(NNTILE_BUILD_${NAME} OFF CACHE BOOL "${DESCRIPTION}" FORCE)
    endif()
endfunction()

if(NNTILE_PRESET STREQUAL "core")
    set(_preset_kernel ON)
    set(_preset_starpu ON)
    set(_preset_core ON)
    set(_preset_graph_base OFF)
    set(_preset_tile OFF)
    set(_preset_tensor OFF)
    set(_preset_nn OFF)
    set(_preset_runtime OFF)
    set(_preset_module OFF)
    set(_preset_model OFF)
    set(_preset_optim OFF)
    set(_preset_io OFF)
    set(_preset_dataset OFF)
elseif(NNTILE_PRESET STREQUAL "graph_min")
    set(_preset_kernel ON)
    set(_preset_starpu ON)
    set(_preset_core ON)
    set(_preset_graph_base ON)
    set(_preset_tile ON)
    set(_preset_tensor ON)
    set(_preset_nn ON)
    set(_preset_runtime ON)
    set(_preset_module OFF)
    set(_preset_model OFF)
    set(_preset_optim OFF)
    set(_preset_io OFF)
    set(_preset_dataset OFF)
elseif(NNTILE_PRESET STREQUAL "full" OR NNTILE_PRESET STREQUAL "")
    set(_preset_kernel ON)
    set(_preset_starpu ON)
    set(_preset_core ON)
    set(_preset_graph_base ON)
    set(_preset_tile ON)
    set(_preset_tensor ON)
    set(_preset_nn ON)
    set(_preset_runtime ON)
    set(_preset_module ON)
    set(_preset_model ON)
    set(_preset_optim ON)
    set(_preset_io ON)
    set(_preset_dataset ON)
else()
    message(FATAL_ERROR "Unknown NNTILE_PRESET=${NNTILE_PRESET}")
endif()

if(NOT NNTILE_COMPILE_CHECK_SUBSYSTEM)
    set(NNTILE_BUILD_KERNEL ${_preset_kernel} CACHE BOOL "Build kernel subsystem" FORCE)
    set(NNTILE_BUILD_STARPU ${_preset_starpu} CACHE BOOL "Build starpu subsystem" FORCE)
    set(NNTILE_BUILD_CORE ${_preset_core} CACHE BOOL "Build core (eager tile) subsystem" FORCE)
    set(NNTILE_BUILD_LOGGER ON CACHE BOOL "Build logger" FORCE)
    set(NNTILE_BUILD_GRAPH_BASE ${_preset_graph_base} CACHE BOOL "Build graph base (dtype)" FORCE)
    set(NNTILE_BUILD_TILE ${_preset_tile} CACHE BOOL "Build tile graph subsystem" FORCE)
    set(NNTILE_BUILD_TENSOR ${_preset_tensor} CACHE BOOL "Build tensor graph subsystem" FORCE)
    set(NNTILE_BUILD_NN ${_preset_nn} CACHE BOOL "Build nn graph subsystem" FORCE)
    set(NNTILE_BUILD_RUNTIME ${_preset_runtime} CACHE BOOL "Build runtime" FORCE)
    set(NNTILE_BUILD_MODULE ${_preset_module} CACHE BOOL "Build module" FORCE)
    set(NNTILE_BUILD_MODEL ${_preset_model} CACHE BOOL "Build model" FORCE)
    set(NNTILE_BUILD_OPTIM ${_preset_optim} CACHE BOOL "Build optim" FORCE)
    set(NNTILE_BUILD_IO ${_preset_io} CACHE BOOL "Build io" FORCE)
    set(NNTILE_BUILD_DATASET ${_preset_dataset} CACHE BOOL "Build dataset" FORCE)
endif()

# Parent/child propagation along the stack
if(NNTILE_BUILD_STARPU AND NOT NNTILE_BUILD_KERNEL)
    set(NNTILE_BUILD_KERNEL ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_CORE AND NOT NNTILE_BUILD_STARPU)
    set(NNTILE_BUILD_STARPU ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_TILE AND NOT NNTILE_BUILD_CORE)
    set(NNTILE_BUILD_CORE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_TILE AND NOT NNTILE_BUILD_GRAPH_BASE)
    set(NNTILE_BUILD_GRAPH_BASE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_TENSOR AND NOT NNTILE_BUILD_TILE)
    set(NNTILE_BUILD_TILE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_NN AND NOT NNTILE_BUILD_TENSOR)
    set(NNTILE_BUILD_TENSOR ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_RUNTIME AND NOT NNTILE_BUILD_NN)
    set(NNTILE_BUILD_NN ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_MODULE AND NOT NNTILE_BUILD_NN)
    set(NNTILE_BUILD_NN ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_OPTIM AND NOT NNTILE_BUILD_NN)
    set(NNTILE_BUILD_NN ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_IO AND NOT NNTILE_BUILD_GRAPH_BASE)
    set(NNTILE_BUILD_GRAPH_BASE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_IO AND NOT NNTILE_BUILD_CORE)
    set(NNTILE_BUILD_CORE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_MODEL AND NOT NNTILE_BUILD_MODULE)
    set(NNTILE_BUILD_MODULE ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_MODEL AND NOT NNTILE_BUILD_RUNTIME)
    set(NNTILE_BUILD_RUNTIME ON CACHE BOOL "" FORCE)
endif()
if(NNTILE_BUILD_DATASET AND NOT NNTILE_BUILD_IO)
    set(NNTILE_BUILD_IO ON CACHE BOOL "" FORCE)
endif()

if(NNTILE_COMPILE_CHECK_SUBSYSTEM)
    foreach(_s IN ITEMS KERNEL STARPU CORE LOGGER GRAPH_BASE TILE TENSOR NN
            RUNTIME MODULE MODEL OPTIM IO DATASET)
        set(NNTILE_BUILD_${_s} OFF CACHE BOOL "" FORCE)
    endforeach()
    string(TOUPPER "${NNTILE_COMPILE_CHECK_SUBSYSTEM}" _cc_upper)
    set(NNTILE_BUILD_${_cc_upper} ON CACHE BOOL "" FORCE)
    if(_cc_upper STREQUAL "TILE" OR _cc_upper STREQUAL "TENSOR"
            OR _cc_upper STREQUAL "NN" OR _cc_upper STREQUAL "IO")
        set(NNTILE_BUILD_GRAPH_BASE ON CACHE BOOL "" FORCE)
    endif()
    if(_cc_upper STREQUAL "TENSOR" OR _cc_upper STREQUAL "NN")
        set(NNTILE_BUILD_TILE ON CACHE BOOL "" FORCE)
    endif()
    if(_cc_upper STREQUAL "NN" OR _cc_upper STREQUAL "RUNTIME"
            OR _cc_upper STREQUAL "MODULE" OR _cc_upper STREQUAL "OPTIM")
        set(NNTILE_BUILD_TENSOR ON CACHE BOOL "" FORCE)
    endif()
    if(NOT _cc_upper STREQUAL "KERNEL")
        set(NNTILE_BUILD_KERNEL ON CACHE BOOL "" FORCE)
    endif()
endif()

function(nntile_enable_subsystems_through LAST)
    set(_order kernel starpu core graph_base tile tensor nn
        runtime module optim io dataset model)
    set(_on ON)
    foreach(_s IN LISTS _order)
        string(TOUPPER "${_s}" _u)
        if(_s STREQUAL "graph_base")
            set(_var GRAPH_BASE)
        else()
            set(_var ${_u})
        endif()
        if(_s STREQUAL "${LAST}")
            set(_on OFF)
        endif()
        if(_on OR _s STREQUAL "${LAST}")
            set(NNTILE_BUILD_${_var} ON CACHE BOOL "" FORCE)
        endif()
    endforeach()
endfunction()
