# CMake generated Testfile for 
# Source directory: /workspace/tests/starpu
# Build directory: /workspace/build-test/tests/starpu
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tests_starpu_accumulate]=] "/workspace/build-test/tests/starpu/test_accumulate")
set_tests_properties([=[tests_starpu_accumulate]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_accumulate_hypot]=] "/workspace/build-test/tests/starpu/test_accumulate_hypot")
set_tests_properties([=[tests_starpu_accumulate_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_accumulate_maxsumexp]=] "/workspace/build-test/tests/starpu/test_accumulate_maxsumexp")
set_tests_properties([=[tests_starpu_accumulate_maxsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_adam_step]=] "/workspace/build-test/tests/starpu/test_adam_step")
set_tests_properties([=[tests_starpu_adam_step]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_adamw_step]=] "/workspace/build-test/tests/starpu/test_adamw_step")
set_tests_properties([=[tests_starpu_adamw_step]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add]=] "/workspace/build-test/tests/starpu/test_add")
set_tests_properties([=[tests_starpu_add]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_fiber]=] "/workspace/build-test/tests/starpu/test_add_fiber")
set_tests_properties([=[tests_starpu_add_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_fiber_inplace]=] "/workspace/build-test/tests/starpu/test_add_fiber_inplace")
set_tests_properties([=[tests_starpu_add_fiber_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_inplace]=] "/workspace/build-test/tests/starpu/test_add_inplace")
set_tests_properties([=[tests_starpu_add_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_scalar]=] "/workspace/build-test/tests/starpu/test_add_scalar")
set_tests_properties([=[tests_starpu_add_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_slice]=] "/workspace/build-test/tests/starpu/test_add_slice")
set_tests_properties([=[tests_starpu_add_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_add_slice_inplace]=] "/workspace/build-test/tests/starpu/test_add_slice_inplace")
set_tests_properties([=[tests_starpu_add_slice_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_addcdiv]=] "/workspace/build-test/tests/starpu/test_addcdiv")
set_tests_properties([=[tests_starpu_addcdiv]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_clear]=] "/workspace/build-test/tests/starpu/test_clear")
set_tests_properties([=[tests_starpu_clear]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_codelet]=] "/workspace/build-test/tests/starpu/test_codelet")
set_tests_properties([=[tests_starpu_codelet]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_conv2d_bwd_input_inplace]=] "/workspace/build-test/tests/starpu/test_conv2d_bwd_input_inplace")
set_tests_properties([=[tests_starpu_conv2d_bwd_input_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_conv2d_bwd_weight_inplace]=] "/workspace/build-test/tests/starpu/test_conv2d_bwd_weight_inplace")
set_tests_properties([=[tests_starpu_conv2d_bwd_weight_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_conv2d_inplace]=] "/workspace/build-test/tests/starpu/test_conv2d_inplace")
set_tests_properties([=[tests_starpu_conv2d_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_copy]=] "/workspace/build-test/tests/starpu/test_copy")
set_tests_properties([=[tests_starpu_copy]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_dgelu]=] "/workspace/build-test/tests/starpu/test_dgelu")
set_tests_properties([=[tests_starpu_dgelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_dgelutanh]=] "/workspace/build-test/tests/starpu/test_dgelutanh")
set_tests_properties([=[tests_starpu_dgelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_drelu]=] "/workspace/build-test/tests/starpu/test_drelu")
set_tests_properties([=[tests_starpu_drelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_embedding]=] "/workspace/build-test/tests/starpu/test_embedding")
set_tests_properties([=[tests_starpu_embedding]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_embedding_backward]=] "/workspace/build-test/tests/starpu/test_embedding_backward")
set_tests_properties([=[tests_starpu_embedding_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_fill]=] "/workspace/build-test/tests/starpu/test_fill")
set_tests_properties([=[tests_starpu_fill]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_flash_attention]=] "/workspace/build-test/tests/starpu/test_flash_attention")
set_tests_properties([=[tests_starpu_flash_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_flash_sdpa_fwd_cudnn]=] "/workspace/build-test/tests/starpu/test_flash_sdpa_fwd_cudnn")
set_tests_properties([=[tests_starpu_flash_sdpa_fwd_cudnn]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gelu]=] "/workspace/build-test/tests/starpu/test_gelu")
set_tests_properties([=[tests_starpu_gelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gelu_backward]=] "/workspace/build-test/tests/starpu/test_gelu_backward")
set_tests_properties([=[tests_starpu_gelu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gelutanh]=] "/workspace/build-test/tests/starpu/test_gelutanh")
set_tests_properties([=[tests_starpu_gelutanh]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gelutanh_backward]=] "/workspace/build-test/tests/starpu/test_gelutanh_backward")
set_tests_properties([=[tests_starpu_gelutanh_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gelutanh_inplace]=] "/workspace/build-test/tests/starpu/test_gelutanh_inplace")
set_tests_properties([=[tests_starpu_gelutanh_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_gemm]=] "/workspace/build-test/tests/starpu/test_gemm")
set_tests_properties([=[tests_starpu_gemm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_handle]=] "/workspace/build-test/tests/starpu/test_handle")
set_tests_properties([=[tests_starpu_handle]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_hypot]=] "/workspace/build-test/tests/starpu/test_hypot")
set_tests_properties([=[tests_starpu_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_hypot_scalar_inverse]=] "/workspace/build-test/tests/starpu/test_hypot_scalar_inverse")
set_tests_properties([=[tests_starpu_hypot_scalar_inverse]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_log_scalar]=] "/workspace/build-test/tests/starpu/test_log_scalar")
set_tests_properties([=[tests_starpu_log_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_logsumexp]=] "/workspace/build-test/tests/starpu/test_logsumexp")
set_tests_properties([=[tests_starpu_logsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_mask_scalar]=] "/workspace/build-test/tests/starpu/test_mask_scalar")
set_tests_properties([=[tests_starpu_mask_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_maximum]=] "/workspace/build-test/tests/starpu/test_maximum")
set_tests_properties([=[tests_starpu_maximum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_maxsumexp]=] "/workspace/build-test/tests/starpu/test_maxsumexp")
set_tests_properties([=[tests_starpu_maxsumexp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_norm_fiber]=] "/workspace/build-test/tests/starpu/test_norm_fiber")
set_tests_properties([=[tests_starpu_norm_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_norm_fiber_inplace]=] "/workspace/build-test/tests/starpu/test_norm_fiber_inplace")
set_tests_properties([=[tests_starpu_norm_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_norm_slice]=] "/workspace/build-test/tests/starpu/test_norm_slice")
set_tests_properties([=[tests_starpu_norm_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_pow]=] "/workspace/build-test/tests/starpu/test_pow")
set_tests_properties([=[tests_starpu_pow]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_prod]=] "/workspace/build-test/tests/starpu/test_prod")
set_tests_properties([=[tests_starpu_prod]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_prod_fiber]=] "/workspace/build-test/tests/starpu/test_prod_fiber")
set_tests_properties([=[tests_starpu_prod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_prod_fiber3]=] "/workspace/build-test/tests/starpu/test_prod_fiber3")
set_tests_properties([=[tests_starpu_prod_fiber3]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_prod_inplace]=] "/workspace/build-test/tests/starpu/test_prod_inplace")
set_tests_properties([=[tests_starpu_prod_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_prod_slice]=] "/workspace/build-test/tests/starpu/test_prod_slice")
set_tests_properties([=[tests_starpu_prod_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_randn]=] "/workspace/build-test/tests/starpu/test_randn")
set_tests_properties([=[tests_starpu_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_relu]=] "/workspace/build-test/tests/starpu/test_relu")
set_tests_properties([=[tests_starpu_relu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_relu_backward]=] "/workspace/build-test/tests/starpu/test_relu_backward")
set_tests_properties([=[tests_starpu_relu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_relu_forward]=] "/workspace/build-test/tests/starpu/test_relu_forward")
set_tests_properties([=[tests_starpu_relu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_rope]=] "/workspace/build-test/tests/starpu/test_rope")
set_tests_properties([=[tests_starpu_rope]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_rope_backward]=] "/workspace/build-test/tests/starpu/test_rope_backward")
set_tests_properties([=[tests_starpu_rope_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_scal]=] "/workspace/build-test/tests/starpu/test_scal")
set_tests_properties([=[tests_starpu_scal]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_scal_inplace]=] "/workspace/build-test/tests/starpu/test_scal_inplace")
set_tests_properties([=[tests_starpu_scal_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_silu_backward]=] "/workspace/build-test/tests/starpu/test_silu_backward")
set_tests_properties([=[tests_starpu_silu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_silu_forward]=] "/workspace/build-test/tests/starpu/test_silu_forward")
set_tests_properties([=[tests_starpu_silu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_softmax]=] "/workspace/build-test/tests/starpu/test_softmax")
set_tests_properties([=[tests_starpu_softmax]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_softmax_inplace]=] "/workspace/build-test/tests/starpu/test_softmax_inplace")
set_tests_properties([=[tests_starpu_softmax_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sqrt]=] "/workspace/build-test/tests/starpu/test_sqrt")
set_tests_properties([=[tests_starpu_sqrt]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sqrt_inplace]=] "/workspace/build-test/tests/starpu/test_sqrt_inplace")
set_tests_properties([=[tests_starpu_sqrt_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_subcopy]=] "/workspace/build-test/tests/starpu/test_subcopy")
set_tests_properties([=[tests_starpu_subcopy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_subtract_indexed_column]=] "/workspace/build-test/tests/starpu/test_subtract_indexed_column")
set_tests_properties([=[tests_starpu_subtract_indexed_column]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_subtract_indexed_outputs]=] "/workspace/build-test/tests/starpu/test_subtract_indexed_outputs")
set_tests_properties([=[tests_starpu_subtract_indexed_outputs]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sum_fiber]=] "/workspace/build-test/tests/starpu/test_sum_fiber")
set_tests_properties([=[tests_starpu_sum_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sum_slice]=] "/workspace/build-test/tests/starpu/test_sum_slice")
set_tests_properties([=[tests_starpu_sum_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sumprod_fiber]=] "/workspace/build-test/tests/starpu/test_sumprod_fiber")
set_tests_properties([=[tests_starpu_sumprod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_sumprod_slice]=] "/workspace/build-test/tests/starpu/test_sumprod_slice")
set_tests_properties([=[tests_starpu_sumprod_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_total_sum_accum]=] "/workspace/build-test/tests/starpu/test_total_sum_accum")
set_tests_properties([=[tests_starpu_total_sum_accum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
add_test([=[tests_starpu_transpose]=] "/workspace/build-test/tests/starpu/test_transpose")
set_tests_properties([=[tests_starpu_transpose]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/starpu/CMakeLists.txt;166;add_test_set;/workspace/tests/starpu/CMakeLists.txt;0;")
