# @copyright (c) 2022-present Skolkovo Institute of Science and Technology
#                              (Skoltech), Russia. All rights reserved.
#                2023-present Artificial Intelligence Research Institute
#                              (AIRI), Russia. All rights reserved.
#
# NNTile is software framework for fast training of big neural networks on
# distributed-memory heterogeneous systems based on StarPU runtime system.
#
# @file wrappers/python/nntile/nntile_core/starpu.pyi
#
# @version 1.1.0

class Config:
    def __init__(self, ncpus: int = ..., ncuda: int = ..., cublas: int = ...,
                 logger_server_addr: str = ...,
                 logger_server_port: int = ...) -> None: ...
    def shutdown(self) -> None: ...

def init() -> None: ...
def pause() -> None: ...
def resume() -> None: ...
def wait_for_all() -> None: ...

def profiling_disable() -> None: ...
def profiling_enable() -> None: ...
def profiling_init() -> None: ...

def restrict_cpu() -> None: ...
def restrict_cuda() -> None: ...
def restrict_restore() -> None: ...
