class Config:

    def __init__(self, ncpus: int = -1, ncuda: int = -1, cublas: int = -1): ...

    def shutdown(self) -> None: ...


def init() -> None: ...
def pause() -> None: ...
def resume() -> None: ...
def wait_for_all() -> None: ...

def profiling_disable() -> None: ...
def profiling_enable() -> None: ...
def profiling_init() -> None: ...
def restrict_cpu() -> None: ...
def restrict_cuda() -> None: ...
def restrict_restore() -> None: ...
