# CMake generated Testfile for 
# Source directory: /workspace/tests/kernel
# Build directory: /workspace/build-test/tests/kernel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tests_kernel_accumulate_maxsumexp]=] "/workspace/build-test/tests/kernel/test_accumulate_maxsumexp")
set_tests_properties([=[tests_kernel_accumulate_maxsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add]=] "/workspace/build-test/tests/kernel/test_add")
set_tests_properties([=[tests_kernel_add]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_fiber]=] "/workspace/build-test/tests/kernel/test_add_fiber")
set_tests_properties([=[tests_kernel_add_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_fiber_inplace]=] "/workspace/build-test/tests/kernel/test_add_fiber_inplace")
set_tests_properties([=[tests_kernel_add_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_inplace]=] "/workspace/build-test/tests/kernel/test_add_inplace")
set_tests_properties([=[tests_kernel_add_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_slice_inplace]=] "/workspace/build-test/tests/kernel/test_add_slice_inplace")
set_tests_properties([=[tests_kernel_add_slice_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_addcdiv]=] "/workspace/build-test/tests/kernel/test_addcdiv")
set_tests_properties([=[tests_kernel_addcdiv]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_conv2d_bwd_input_inplace]=] "/workspace/build-test/tests/kernel/test_conv2d_bwd_input_inplace")
set_tests_properties([=[tests_kernel_conv2d_bwd_input_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_conv2d_bwd_weight_inplace]=] "/workspace/build-test/tests/kernel/test_conv2d_bwd_weight_inplace")
set_tests_properties([=[tests_kernel_conv2d_bwd_weight_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_conv2d_inplace]=] "/workspace/build-test/tests/kernel/test_conv2d_inplace")
set_tests_properties([=[tests_kernel_conv2d_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_dgelu]=] "/workspace/build-test/tests/kernel/test_dgelu")
set_tests_properties([=[tests_kernel_dgelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_dgelutanh]=] "/workspace/build-test/tests/kernel/test_dgelutanh")
set_tests_properties([=[tests_kernel_dgelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_drelu]=] "/workspace/build-test/tests/kernel/test_drelu")
set_tests_properties([=[tests_kernel_drelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_embedding]=] "/workspace/build-test/tests/kernel/test_embedding")
set_tests_properties([=[tests_kernel_embedding]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_embedding_backward]=] "/workspace/build-test/tests/kernel/test_embedding_backward")
set_tests_properties([=[tests_kernel_embedding_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_fill]=] "/workspace/build-test/tests/kernel/test_fill")
set_tests_properties([=[tests_kernel_fill]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_gelu]=] "/workspace/build-test/tests/kernel/test_gelu")
set_tests_properties([=[tests_kernel_gelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_gelutanh_inplace]=] "/workspace/build-test/tests/kernel/test_gelutanh_inplace")
set_tests_properties([=[tests_kernel_gelutanh_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_hypot]=] "/workspace/build-test/tests/kernel/test_hypot")
set_tests_properties([=[tests_kernel_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_hypot_scalar_inverse]=] "/workspace/build-test/tests/kernel/test_hypot_scalar_inverse")
set_tests_properties([=[tests_kernel_hypot_scalar_inverse]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_logsumexp]=] "/workspace/build-test/tests/kernel/test_logsumexp")
set_tests_properties([=[tests_kernel_logsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_mask_scalar]=] "/workspace/build-test/tests/kernel/test_mask_scalar")
set_tests_properties([=[tests_kernel_mask_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_maximum]=] "/workspace/build-test/tests/kernel/test_maximum")
set_tests_properties([=[tests_kernel_maximum]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_norm_fiber]=] "/workspace/build-test/tests/kernel/test_norm_fiber")
set_tests_properties([=[tests_kernel_norm_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_norm_fiber_inplace]=] "/workspace/build-test/tests/kernel/test_norm_fiber_inplace")
set_tests_properties([=[tests_kernel_norm_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_norm_slice]=] "/workspace/build-test/tests/kernel/test_norm_slice")
set_tests_properties([=[tests_kernel_norm_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_pow]=] "/workspace/build-test/tests/kernel/test_pow")
set_tests_properties([=[tests_kernel_pow]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_prod]=] "/workspace/build-test/tests/kernel/test_prod")
set_tests_properties([=[tests_kernel_prod]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_prod_fiber]=] "/workspace/build-test/tests/kernel/test_prod_fiber")
set_tests_properties([=[tests_kernel_prod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_prod_fiber3]=] "/workspace/build-test/tests/kernel/test_prod_fiber3")
set_tests_properties([=[tests_kernel_prod_fiber3]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_prod_inplace]=] "/workspace/build-test/tests/kernel/test_prod_inplace")
set_tests_properties([=[tests_kernel_prod_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_prod_slice]=] "/workspace/build-test/tests/kernel/test_prod_slice")
set_tests_properties([=[tests_kernel_prod_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_randn]=] "/workspace/build-test/tests/kernel/test_randn")
set_tests_properties([=[tests_kernel_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_relu]=] "/workspace/build-test/tests/kernel/test_relu")
set_tests_properties([=[tests_kernel_relu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_rope]=] "/workspace/build-test/tests/kernel/test_rope")
set_tests_properties([=[tests_kernel_rope]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_rope_backward]=] "/workspace/build-test/tests/kernel/test_rope_backward")
set_tests_properties([=[tests_kernel_rope_backward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_scal]=] "/workspace/build-test/tests/kernel/test_scal")
set_tests_properties([=[tests_kernel_scal]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_scal_inplace]=] "/workspace/build-test/tests/kernel/test_scal_inplace")
set_tests_properties([=[tests_kernel_scal_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_softmax]=] "/workspace/build-test/tests/kernel/test_softmax")
set_tests_properties([=[tests_kernel_softmax]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_softmax_inplace]=] "/workspace/build-test/tests/kernel/test_softmax_inplace")
set_tests_properties([=[tests_kernel_softmax_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sqrt]=] "/workspace/build-test/tests/kernel/test_sqrt")
set_tests_properties([=[tests_kernel_sqrt]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sqrt_inplace]=] "/workspace/build-test/tests/kernel/test_sqrt_inplace")
set_tests_properties([=[tests_kernel_sqrt_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_subcopy]=] "/workspace/build-test/tests/kernel/test_subcopy")
set_tests_properties([=[tests_kernel_subcopy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_subtract_indexed_column]=] "/workspace/build-test/tests/kernel/test_subtract_indexed_column")
set_tests_properties([=[tests_kernel_subtract_indexed_column]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_subtract_indexed_outputs]=] "/workspace/build-test/tests/kernel/test_subtract_indexed_outputs")
set_tests_properties([=[tests_kernel_subtract_indexed_outputs]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sum_fiber]=] "/workspace/build-test/tests/kernel/test_sum_fiber")
set_tests_properties([=[tests_kernel_sum_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sum_slice]=] "/workspace/build-test/tests/kernel/test_sum_slice")
set_tests_properties([=[tests_kernel_sum_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sumprod_fiber]=] "/workspace/build-test/tests/kernel/test_sumprod_fiber")
set_tests_properties([=[tests_kernel_sumprod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_sumprod_slice]=] "/workspace/build-test/tests/kernel/test_sumprod_slice")
set_tests_properties([=[tests_kernel_sumprod_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_total_sum_accum]=] "/workspace/build-test/tests/kernel/test_total_sum_accum")
set_tests_properties([=[tests_kernel_total_sum_accum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_transpose]=] "/workspace/build-test/tests/kernel/test_transpose")
set_tests_properties([=[tests_kernel_transpose]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;109;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_adam_step]=] "/workspace/build-test/tests/kernel/test_adam_step")
set_tests_properties([=[tests_kernel_adam_step]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_adamw_step]=] "/workspace/build-test/tests/kernel/test_adamw_step")
set_tests_properties([=[tests_kernel_adamw_step]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_scalar]=] "/workspace/build-test/tests/kernel/test_add_scalar")
set_tests_properties([=[tests_kernel_add_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_add_slice]=] "/workspace/build-test/tests/kernel/test_add_slice")
set_tests_properties([=[tests_kernel_add_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_flash_attention]=] "/workspace/build-test/tests/kernel/test_flash_attention")
set_tests_properties([=[tests_kernel_flash_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_gelu_backward]=] "/workspace/build-test/tests/kernel/test_gelu_backward")
set_tests_properties([=[tests_kernel_gelu_backward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_gelutanh]=] "/workspace/build-test/tests/kernel/test_gelutanh")
set_tests_properties([=[tests_kernel_gelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_gelutanh_backward]=] "/workspace/build-test/tests/kernel/test_gelutanh_backward")
set_tests_properties([=[tests_kernel_gelutanh_backward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_relu_backward]=] "/workspace/build-test/tests/kernel/test_relu_backward")
set_tests_properties([=[tests_kernel_relu_backward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_relu_forward]=] "/workspace/build-test/tests/kernel/test_relu_forward")
set_tests_properties([=[tests_kernel_relu_forward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_silu_backward]=] "/workspace/build-test/tests/kernel/test_silu_backward")
set_tests_properties([=[tests_kernel_silu_backward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
add_test([=[tests_kernel_silu_forward]=] "/workspace/build-test/tests/kernel/test_silu_forward")
set_tests_properties([=[tests_kernel_silu_forward]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/kernel/CMakeLists.txt;140;add_test_set;/workspace/tests/kernel/CMakeLists.txt;0;")
