# @copyright (c) 2026-present Skolkovo Institute of Science and Technology
#                              (Skoltech), Russia. All rights reserved.
#
# @file torch_nntile/torch_nntile/_build_info.py
# Generated by setup.py - do not edit by hand for wheels.

"""Compile-time configuration baked into the install."""

from __future__ import annotations

BUILT_WITH_CUDA = False
TORCH_NATIVE_OPS = True
NNTILE_NATIVE_OPS = True
