# CMake generated Testfile for 
# Source directory: /workspace/tests/tensor
# Build directory: /workspace/build-test/tests/tensor
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tests_tensor_traits]=] "/workspace/build-test/tests/tensor/test_traits")
set_tests_properties([=[tests_tensor_traits]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;139;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_distributions]=] "/workspace/build-test/tests/tensor/test_distributions")
set_tests_properties([=[tests_tensor_distributions]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;139;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add]=] "/workspace/build-test/tests/tensor/test_add")
set_tests_properties([=[tests_tensor_add]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_fiber]=] "/workspace/build-test/tests/tensor/test_add_fiber")
set_tests_properties([=[tests_tensor_add_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_fiber_inplace]=] "/workspace/build-test/tests/tensor/test_add_fiber_inplace")
set_tests_properties([=[tests_tensor_add_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_inplace]=] "/workspace/build-test/tests/tensor/test_add_inplace")
set_tests_properties([=[tests_tensor_add_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_scalar]=] "/workspace/build-test/tests/tensor/test_add_scalar")
set_tests_properties([=[tests_tensor_add_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_slice]=] "/workspace/build-test/tests/tensor/test_add_slice")
set_tests_properties([=[tests_tensor_add_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_add_slice_inplace]=] "/workspace/build-test/tests/tensor/test_add_slice_inplace")
set_tests_properties([=[tests_tensor_add_slice_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_addcdiv]=] "/workspace/build-test/tests/tensor/test_addcdiv")
set_tests_properties([=[tests_tensor_addcdiv]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_adam_step]=] "/workspace/build-test/tests/tensor/test_adam_step")
set_tests_properties([=[tests_tensor_adam_step]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_adamw_step]=] "/workspace/build-test/tests/tensor/test_adamw_step")
set_tests_properties([=[tests_tensor_adamw_step]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_clear]=] "/workspace/build-test/tests/tensor/test_clear")
set_tests_properties([=[tests_tensor_clear]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_conv2d_bwd_input_inplace]=] "/workspace/build-test/tests/tensor/test_conv2d_bwd_input_inplace")
set_tests_properties([=[tests_tensor_conv2d_bwd_input_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_conv2d_bwd_weight_inplace]=] "/workspace/build-test/tests/tensor/test_conv2d_bwd_weight_inplace")
set_tests_properties([=[tests_tensor_conv2d_bwd_weight_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_conv2d_inplace]=] "/workspace/build-test/tests/tensor/test_conv2d_inplace")
set_tests_properties([=[tests_tensor_conv2d_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_copy]=] "/workspace/build-test/tests/tensor/test_copy")
set_tests_properties([=[tests_tensor_copy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_copy_intersection]=] "/workspace/build-test/tests/tensor/test_copy_intersection")
set_tests_properties([=[tests_tensor_copy_intersection]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_dgelu]=] "/workspace/build-test/tests/tensor/test_dgelu")
set_tests_properties([=[tests_tensor_dgelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_dgelutanh]=] "/workspace/build-test/tests/tensor/test_dgelutanh")
set_tests_properties([=[tests_tensor_dgelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_drelu]=] "/workspace/build-test/tests/tensor/test_drelu")
set_tests_properties([=[tests_tensor_drelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_embedding]=] "/workspace/build-test/tests/tensor/test_embedding")
set_tests_properties([=[tests_tensor_embedding]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_embedding_backward]=] "/workspace/build-test/tests/tensor/test_embedding_backward")
set_tests_properties([=[tests_tensor_embedding_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_fill]=] "/workspace/build-test/tests/tensor/test_fill")
set_tests_properties([=[tests_tensor_fill]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gather]=] "/workspace/build-test/tests/tensor/test_gather")
set_tests_properties([=[tests_tensor_gather]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gelu]=] "/workspace/build-test/tests/tensor/test_gelu")
set_tests_properties([=[tests_tensor_gelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gelu_backward]=] "/workspace/build-test/tests/tensor/test_gelu_backward")
set_tests_properties([=[tests_tensor_gelu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gelutanh]=] "/workspace/build-test/tests/tensor/test_gelutanh")
set_tests_properties([=[tests_tensor_gelutanh]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gelutanh_backward]=] "/workspace/build-test/tests/tensor/test_gelutanh_backward")
set_tests_properties([=[tests_tensor_gelutanh_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gelutanh_inplace]=] "/workspace/build-test/tests/tensor/test_gelutanh_inplace")
set_tests_properties([=[tests_tensor_gelutanh_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_gemm]=] "/workspace/build-test/tests/tensor/test_gemm")
set_tests_properties([=[tests_tensor_gemm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_hypot]=] "/workspace/build-test/tests/tensor/test_hypot")
set_tests_properties([=[tests_tensor_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_hypot_scalar_inverse]=] "/workspace/build-test/tests/tensor/test_hypot_scalar_inverse")
set_tests_properties([=[tests_tensor_hypot_scalar_inverse]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_log_scalar]=] "/workspace/build-test/tests/tensor/test_log_scalar")
set_tests_properties([=[tests_tensor_log_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_logsumexp]=] "/workspace/build-test/tests/tensor/test_logsumexp")
set_tests_properties([=[tests_tensor_logsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_mask_scalar]=] "/workspace/build-test/tests/tensor/test_mask_scalar")
set_tests_properties([=[tests_tensor_mask_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_maximum]=] "/workspace/build-test/tests/tensor/test_maximum")
set_tests_properties([=[tests_tensor_maximum]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_maxsumexp]=] "/workspace/build-test/tests/tensor/test_maxsumexp")
set_tests_properties([=[tests_tensor_maxsumexp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_norm_fiber]=] "/workspace/build-test/tests/tensor/test_norm_fiber")
set_tests_properties([=[tests_tensor_norm_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_norm_fiber_inplace]=] "/workspace/build-test/tests/tensor/test_norm_fiber_inplace")
set_tests_properties([=[tests_tensor_norm_fiber_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_norm_slice]=] "/workspace/build-test/tests/tensor/test_norm_slice")
set_tests_properties([=[tests_tensor_norm_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_pow]=] "/workspace/build-test/tests/tensor/test_pow")
set_tests_properties([=[tests_tensor_pow]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_prod]=] "/workspace/build-test/tests/tensor/test_prod")
set_tests_properties([=[tests_tensor_prod]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_prod_fiber]=] "/workspace/build-test/tests/tensor/test_prod_fiber")
set_tests_properties([=[tests_tensor_prod_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_prod_fiber3]=] "/workspace/build-test/tests/tensor/test_prod_fiber3")
set_tests_properties([=[tests_tensor_prod_fiber3]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_prod_inplace]=] "/workspace/build-test/tests/tensor/test_prod_inplace")
set_tests_properties([=[tests_tensor_prod_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_prod_slice]=] "/workspace/build-test/tests/tensor/test_prod_slice")
set_tests_properties([=[tests_tensor_prod_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_randn]=] "/workspace/build-test/tests/tensor/test_randn")
set_tests_properties([=[tests_tensor_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_relu]=] "/workspace/build-test/tests/tensor/test_relu")
set_tests_properties([=[tests_tensor_relu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_relu_backward]=] "/workspace/build-test/tests/tensor/test_relu_backward")
set_tests_properties([=[tests_tensor_relu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_relu_forward]=] "/workspace/build-test/tests/tensor/test_relu_forward")
set_tests_properties([=[tests_tensor_relu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_rope]=] "/workspace/build-test/tests/tensor/test_rope")
set_tests_properties([=[tests_tensor_rope]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_rope_backward]=] "/workspace/build-test/tests/tensor/test_rope_backward")
set_tests_properties([=[tests_tensor_rope_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_scal]=] "/workspace/build-test/tests/tensor/test_scal")
set_tests_properties([=[tests_tensor_scal]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_scal_inplace]=] "/workspace/build-test/tests/tensor/test_scal_inplace")
set_tests_properties([=[tests_tensor_scal_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_scatter]=] "/workspace/build-test/tests/tensor/test_scatter")
set_tests_properties([=[tests_tensor_scatter]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_silu_backward]=] "/workspace/build-test/tests/tensor/test_silu_backward")
set_tests_properties([=[tests_tensor_silu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_silu_forward]=] "/workspace/build-test/tests/tensor/test_silu_forward")
set_tests_properties([=[tests_tensor_silu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_softmax]=] "/workspace/build-test/tests/tensor/test_softmax")
set_tests_properties([=[tests_tensor_softmax]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_softmax_inplace]=] "/workspace/build-test/tests/tensor/test_softmax_inplace")
set_tests_properties([=[tests_tensor_softmax_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sqrt]=] "/workspace/build-test/tests/tensor/test_sqrt")
set_tests_properties([=[tests_tensor_sqrt]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sqrt_inplace]=] "/workspace/build-test/tests/tensor/test_sqrt_inplace")
set_tests_properties([=[tests_tensor_sqrt_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_subtract_indexed_column]=] "/workspace/build-test/tests/tensor/test_subtract_indexed_column")
set_tests_properties([=[tests_tensor_subtract_indexed_column]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_subtract_indexed_outputs]=] "/workspace/build-test/tests/tensor/test_subtract_indexed_outputs")
set_tests_properties([=[tests_tensor_subtract_indexed_outputs]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sum_fiber]=] "/workspace/build-test/tests/tensor/test_sum_fiber")
set_tests_properties([=[tests_tensor_sum_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sum_slice]=] "/workspace/build-test/tests/tensor/test_sum_slice")
set_tests_properties([=[tests_tensor_sum_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sumprod_fiber]=] "/workspace/build-test/tests/tensor/test_sumprod_fiber")
set_tests_properties([=[tests_tensor_sumprod_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_sumprod_slice]=] "/workspace/build-test/tests/tensor/test_sumprod_slice")
set_tests_properties([=[tests_tensor_sumprod_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_tensor]=] "/workspace/build-test/tests/tensor/test_tensor")
set_tests_properties([=[tests_tensor_tensor]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_total_sum_accum]=] "/workspace/build-test/tests/tensor/test_total_sum_accum")
set_tests_properties([=[tests_tensor_total_sum_accum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
add_test([=[tests_tensor_transpose]=] "/workspace/build-test/tests/tensor/test_transpose")
set_tests_properties([=[tests_tensor_transpose]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tensor/CMakeLists.txt;155;add_test_set;/workspace/tests/tensor/CMakeLists.txt;0;")
