# CMake generated Testfile for 
# Source directory: /workspace/tests/tile
# Build directory: /workspace/build-test/tests/tile
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tests_tile_add]=] "/workspace/build-test/tests/tile/test_add")
set_tests_properties([=[tests_tile_add]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_add_fiber_inplace]=] "/workspace/build-test/tests/tile/test_add_fiber_inplace")
set_tests_properties([=[tests_tile_add_fiber_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_add_fiber]=] "/workspace/build-test/tests/tile/test_add_fiber")
set_tests_properties([=[tests_tile_add_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_add_scalar]=] "/workspace/build-test/tests/tile/test_add_scalar")
set_tests_properties([=[tests_tile_add_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_add_slice_inplace]=] "/workspace/build-test/tests/tile/test_add_slice_inplace")
set_tests_properties([=[tests_tile_add_slice_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_add_slice]=] "/workspace/build-test/tests/tile/test_add_slice")
set_tests_properties([=[tests_tile_add_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_addcdiv]=] "/workspace/build-test/tests/tile/test_addcdiv")
set_tests_properties([=[tests_tile_addcdiv]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_clear]=] "/workspace/build-test/tests/tile/test_clear")
set_tests_properties([=[tests_tile_clear]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_copy]=] "/workspace/build-test/tests/tile/test_copy")
set_tests_properties([=[tests_tile_copy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_copy_intersection]=] "/workspace/build-test/tests/tile/test_copy_intersection")
set_tests_properties([=[tests_tile_copy_intersection]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_dgelu]=] "/workspace/build-test/tests/tile/test_dgelu")
set_tests_properties([=[tests_tile_dgelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_dgelutanh]=] "/workspace/build-test/tests/tile/test_dgelutanh")
set_tests_properties([=[tests_tile_dgelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_drelu]=] "/workspace/build-test/tests/tile/test_drelu")
set_tests_properties([=[tests_tile_drelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_fill]=] "/workspace/build-test/tests/tile/test_fill")
set_tests_properties([=[tests_tile_fill]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gelu]=] "/workspace/build-test/tests/tile/test_gelu")
set_tests_properties([=[tests_tile_gelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gelu_backward]=] "/workspace/build-test/tests/tile/test_gelu_backward")
set_tests_properties([=[tests_tile_gelu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gelutanh]=] "/workspace/build-test/tests/tile/test_gelutanh")
set_tests_properties([=[tests_tile_gelutanh]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gelutanh_inplace]=] "/workspace/build-test/tests/tile/test_gelutanh_inplace")
set_tests_properties([=[tests_tile_gelutanh_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gelutanh_backward]=] "/workspace/build-test/tests/tile/test_gelutanh_backward")
set_tests_properties([=[tests_tile_gelutanh_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_gemm]=] "/workspace/build-test/tests/tile/test_gemm")
set_tests_properties([=[tests_tile_gemm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_logsumexp]=] "/workspace/build-test/tests/tile/test_logsumexp")
set_tests_properties([=[tests_tile_logsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_mask_scalar]=] "/workspace/build-test/tests/tile/test_mask_scalar")
set_tests_properties([=[tests_tile_mask_scalar]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_maximum]=] "/workspace/build-test/tests/tile/test_maximum")
set_tests_properties([=[tests_tile_maximum]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_maxsumexp]=] "/workspace/build-test/tests/tile/test_maxsumexp")
set_tests_properties([=[tests_tile_maxsumexp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_norm_fiber]=] "/workspace/build-test/tests/tile/test_norm_fiber")
set_tests_properties([=[tests_tile_norm_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_norm_fiber_inplace]=] "/workspace/build-test/tests/tile/test_norm_fiber_inplace")
set_tests_properties([=[tests_tile_norm_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_norm_slice]=] "/workspace/build-test/tests/tile/test_norm_slice")
set_tests_properties([=[tests_tile_norm_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_pow]=] "/workspace/build-test/tests/tile/test_pow")
set_tests_properties([=[tests_tile_pow]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_prod_inplace]=] "/workspace/build-test/tests/tile/test_prod_inplace")
set_tests_properties([=[tests_tile_prod_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_prod_fiber]=] "/workspace/build-test/tests/tile/test_prod_fiber")
set_tests_properties([=[tests_tile_prod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_prod_fiber3]=] "/workspace/build-test/tests/tile/test_prod_fiber3")
set_tests_properties([=[tests_tile_prod_fiber3]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_prod_slice]=] "/workspace/build-test/tests/tile/test_prod_slice")
set_tests_properties([=[tests_tile_prod_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_randn]=] "/workspace/build-test/tests/tile/test_randn")
set_tests_properties([=[tests_tile_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_relu]=] "/workspace/build-test/tests/tile/test_relu")
set_tests_properties([=[tests_tile_relu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_relu_backward]=] "/workspace/build-test/tests/tile/test_relu_backward")
set_tests_properties([=[tests_tile_relu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_relu_forward]=] "/workspace/build-test/tests/tile/test_relu_forward")
set_tests_properties([=[tests_tile_relu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_rope]=] "/workspace/build-test/tests/tile/test_rope")
set_tests_properties([=[tests_tile_rope]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_scal_inplace]=] "/workspace/build-test/tests/tile/test_scal_inplace")
set_tests_properties([=[tests_tile_scal_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_silu_backward]=] "/workspace/build-test/tests/tile/test_silu_backward")
set_tests_properties([=[tests_tile_silu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_silu_forward]=] "/workspace/build-test/tests/tile/test_silu_forward")
set_tests_properties([=[tests_tile_silu_forward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_softmax]=] "/workspace/build-test/tests/tile/test_softmax")
set_tests_properties([=[tests_tile_softmax]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_softmax_inplace]=] "/workspace/build-test/tests/tile/test_softmax_inplace")
set_tests_properties([=[tests_tile_softmax_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sqrt]=] "/workspace/build-test/tests/tile/test_sqrt")
set_tests_properties([=[tests_tile_sqrt]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sqrt_inplace]=] "/workspace/build-test/tests/tile/test_sqrt_inplace")
set_tests_properties([=[tests_tile_sqrt_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_subtract_indexed_column]=] "/workspace/build-test/tests/tile/test_subtract_indexed_column")
set_tests_properties([=[tests_tile_subtract_indexed_column]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_subtract_indexed_outputs]=] "/workspace/build-test/tests/tile/test_subtract_indexed_outputs")
set_tests_properties([=[tests_tile_subtract_indexed_outputs]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sum_fiber]=] "/workspace/build-test/tests/tile/test_sum_fiber")
set_tests_properties([=[tests_tile_sum_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sum_slice]=] "/workspace/build-test/tests/tile/test_sum_slice")
set_tests_properties([=[tests_tile_sum_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sumprod_fiber]=] "/workspace/build-test/tests/tile/test_sumprod_fiber")
set_tests_properties([=[tests_tile_sumprod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_sumprod_slice]=] "/workspace/build-test/tests/tile/test_sumprod_slice")
set_tests_properties([=[tests_tile_sumprod_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_tile]=] "/workspace/build-test/tests/tile/test_tile")
set_tests_properties([=[tests_tile_tile]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_total_sum_accum]=] "/workspace/build-test/tests/tile/test_total_sum_accum")
set_tests_properties([=[tests_tile_total_sum_accum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_traits]=] "/workspace/build-test/tests/tile/test_traits")
set_tests_properties([=[tests_tile_traits]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_scal]=] "/workspace/build-test/tests/tile/test_scal")
set_tests_properties([=[tests_tile_scal]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
add_test([=[tests_tile_hypot]=] "/workspace/build-test/tests/tile/test_hypot")
set_tests_properties([=[tests_tile_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;102;add_test;/workspace/tests/tile/CMakeLists.txt;118;add_test_set;/workspace/tests/tile/CMakeLists.txt;0;")
