# CMake generated Testfile for 
# Source directory: /workspace/wrappers/python
# Build directory: /workspace/build-test/wrappers/python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[wrappers_python_tests_layer_act]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_act.py")
set_tests_properties([=[wrappers_python_tests_layer_act]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_add]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_add.py")
set_tests_properties([=[wrappers_python_tests_layer_add]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_add_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_add_slice.py")
set_tests_properties([=[wrappers_python_tests_layer_add_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_batch_norm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_batch_norm.py")
set_tests_properties([=[wrappers_python_tests_layer_batch_norm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_bert_selfattention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_bert_selfattention.py")
set_tests_properties([=[wrappers_python_tests_layer_bert_selfattention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_conv2d]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_conv2d.py")
set_tests_properties([=[wrappers_python_tests_layer_conv2d]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_embedding]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_embedding.py")
set_tests_properties([=[wrappers_python_tests_layer_embedding]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_gap]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_gap.py")
set_tests_properties([=[wrappers_python_tests_layer_gap]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_gpt2_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_gpt2_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_gpt2_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_gpt2mlp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_gpt2mlp.py")
set_tests_properties([=[wrappers_python_tests_layer_gpt2mlp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_gpt_neo_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_gpt_neo_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_gpt_neo_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_gpt_neox_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_gpt_neox_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_gpt_neox_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_layer_norm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_layer_norm.py")
set_tests_properties([=[wrappers_python_tests_layer_layer_norm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_linear]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_linear.py")
set_tests_properties([=[wrappers_python_tests_layer_linear]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_llama_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_llama_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_llama_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_mixer_against_torch]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_mixer_against_torch.py")
set_tests_properties([=[wrappers_python_tests_layer_mixer_against_torch]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_mixer_mlp_against_torch]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_mixer_mlp_against_torch.py")
set_tests_properties([=[wrappers_python_tests_layer_mixer_mlp_against_torch]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_rms_norm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_rms_norm.py")
set_tests_properties([=[wrappers_python_tests_layer_rms_norm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_layer_t5_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/layer/test_t5_attention.py")
set_tests_properties([=[wrappers_python_tests_layer_t5_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_loss_frob]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/loss/test_frob.py")
set_tests_properties([=[wrappers_python_tests_loss_frob]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_loss_xentropy]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/loss/test_xentropy.py")
set_tests_properties([=[wrappers_python_tests_loss_xentropy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model/generation_llm_samplers]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/generation/test_llm_samplers.py")
set_tests_properties([=[wrappers_python_tests_model/generation_llm_samplers]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_attention]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_attention.py")
set_tests_properties([=[wrappers_python_tests_model_bert_attention]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_embeddings]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_embeddings.py")
set_tests_properties([=[wrappers_python_tests_model_bert_embeddings]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_encoder]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_encoder.py")
set_tests_properties([=[wrappers_python_tests_model_bert_encoder]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_for_masked_lm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_for_masked_lm.py")
set_tests_properties([=[wrappers_python_tests_model_bert_for_masked_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_intermediate]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_intermediate.py")
set_tests_properties([=[wrappers_python_tests_model_bert_intermediate]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_layer]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_layer.py")
set_tests_properties([=[wrappers_python_tests_model_bert_layer]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_lm_pred_head]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_lm_pred_head.py")
set_tests_properties([=[wrappers_python_tests_model_bert_lm_pred_head]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_model]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_model.py")
set_tests_properties([=[wrappers_python_tests_model_bert_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_output]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_output.py")
set_tests_properties([=[wrappers_python_tests_model_bert_output]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_pred_head_trans]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_pred_head_trans.py")
set_tests_properties([=[wrappers_python_tests_model_bert_pred_head_trans]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_bert_selfoutput]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_bert_selfoutput.py")
set_tests_properties([=[wrappers_python_tests_model_bert_selfoutput]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_deep_relu]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_deep_relu.py")
set_tests_properties([=[wrappers_python_tests_model_deep_relu]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_generate]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_generate.py")
set_tests_properties([=[wrappers_python_tests_model_generate]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt2]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt2.py")
set_tests_properties([=[wrappers_python_tests_model_gpt2]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt2_block]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt2_block.py")
set_tests_properties([=[wrappers_python_tests_model_gpt2_block]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt2_lmhead]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt2_lmhead.py")
set_tests_properties([=[wrappers_python_tests_model_gpt2_lmhead]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt2_mlp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt2_mlp.py")
set_tests_properties([=[wrappers_python_tests_model_gpt2_mlp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt2_model]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt2_model.py")
set_tests_properties([=[wrappers_python_tests_model_gpt2_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neo_block]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neo_block.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neo_block]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neo_causal]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neo_causal.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neo_causal]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neo_mlp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neo_mlp.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neo_mlp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neo_model]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neo_model.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neo_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neox_block]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neox_block.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neox_block]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neox_causal]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neox_causal.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neox_causal]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neox_mlp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neox_mlp.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neox_mlp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_gpt_neox_model]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_gpt_neox_model.py")
set_tests_properties([=[wrappers_python_tests_model_gpt_neox_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_llama]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_llama.py")
set_tests_properties([=[wrappers_python_tests_model_llama]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_llama_causal]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_llama_causal.py")
set_tests_properties([=[wrappers_python_tests_model_llama_causal]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_llama_decoder]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_llama_decoder.py")
set_tests_properties([=[wrappers_python_tests_model_llama_decoder]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_llama_mlp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_llama_mlp.py")
set_tests_properties([=[wrappers_python_tests_model_llama_mlp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_mlp_mixer_against_torch]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_mlp_mixer_against_torch.py")
set_tests_properties([=[wrappers_python_tests_model_mlp_mixer_against_torch]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_roberta_for_masked_lm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_roberta_for_masked_lm.py")
set_tests_properties([=[wrappers_python_tests_model_roberta_for_masked_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_roberta_lm_head]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_roberta_lm_head.py")
set_tests_properties([=[wrappers_python_tests_model_roberta_lm_head]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_sync_llm_engine]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_sync_llm_engine.py")
set_tests_properties([=[wrappers_python_tests_model_sync_llm_engine]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_t5_block]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_t5_block.py")
set_tests_properties([=[wrappers_python_tests_model_t5_block]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_t5_ff]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_t5_ff.py")
set_tests_properties([=[wrappers_python_tests_model_t5_ff]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_t5_lmhead]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_t5_lmhead.py")
set_tests_properties([=[wrappers_python_tests_model_t5_lmhead]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_model_t5_model]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/model/test_t5_model.py")
set_tests_properties([=[wrappers_python_tests_model_t5_model]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_add_fiber_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_add_fiber_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_add_fiber_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_add_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_add_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_add_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_add_scalar]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_add_scalar.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_add_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_add_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_add_slice.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_add_slice]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_add_slice_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_add_slice_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_add_slice_inplace]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_addcdiv]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_addcdiv.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_addcdiv]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_clear]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_clear.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_clear]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_conv2d_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_conv2d_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_conv2d_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_copy]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_copy.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_copy]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_copy_intersection]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_copy_intersection.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_copy_intersection]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_dgelu]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_dgelu.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_dgelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_dgelutanh]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_dgelutanh.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_dgelutanh]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_drelu]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_drelu.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_drelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_fill]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_fill.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_fill]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gather]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gather.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gather]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gelu]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gelu.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gelu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gelu_backward]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gelu_backward.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gelu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gelutanh_backward]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gelutanh_backward.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gelutanh_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gelutanh_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gelutanh_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gelutanh_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_gemm]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_gemm.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_gemm]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_hypot]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_hypot.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_hypot]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_logsumexp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_logsumexp.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_logsumexp]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_mask_scalar]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_mask_scalar.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_mask_scalar]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_maximum]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_maximum.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_maximum]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_maxsumexp]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_maxsumexp.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_maxsumexp]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_norm_fiber]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_norm_fiber.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_norm_fiber]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_norm_fiber_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_norm_fiber_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_norm_fiber_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_norm_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_norm_slice.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_norm_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_pow]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_pow.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_pow]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_prod]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_prod.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_prod]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_prod_fiber]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_prod_fiber.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_prod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_prod_fiber3]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_prod_fiber3.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_prod_fiber3]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_prod_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_prod_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_prod_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_prod_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_prod_slice.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_prod_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_randn]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_randn.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_randn]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_relu]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_relu.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_relu]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_relu_backward]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_relu_backward.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_relu_backward]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_scal]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_scal.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_scal]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_scal_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_scal_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_scal_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_scatter]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_scatter.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_scatter]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_softmax_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_softmax_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_softmax_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_sqrt_inplace]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_sqrt_inplace.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_sqrt_inplace]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_subtract_indexed_column]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_subtract_indexed_column.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_subtract_indexed_column]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_sum_fiber]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_sum_fiber.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_sum_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_sum_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_sum_slice.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_sum_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_sumprod_fiber]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_sumprod_fiber.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_sumprod_fiber]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_sumprod_slice]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_sumprod_slice.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_sumprod_slice]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tensor_total_sum_accum]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tensor_total_sum_accum.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tensor_total_sum_accum]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_nntile_core_tile]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/nntile_core/test_tile.py")
set_tests_properties([=[wrappers_python_tests_nntile_core_tile]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
add_test([=[wrappers_python_tests_optimizer_adam]=] "/usr/bin/python3" "-m" "pytest" "-rx" "/workspace/build-test/wrappers/python/tests/optimizer/test_adam.py")
set_tests_properties([=[wrappers_python_tests_optimizer_adam]=] PROPERTIES  LABELS "NotImplemented" _BACKTRACE_TRIPLES "/workspace/wrappers/python/CMakeLists.txt;89;add_test;/workspace/wrappers/python/CMakeLists.txt;0;")
subdirs("pybind11")
