name: Build and test

on:
  push:
    branches:
      - main
      - graph_api
  pull_request:
    branches:
      - main
      - graph_api

permissions:
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      is-pull-request: ${{ github.event_name == 'pull_request' }}
