name: Nightly build

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      is-pull-request: false
